### PR TITLE
Refactor message types and driver

### PR DESCRIPTION
**Pull request by gozmanyoni**
Tried to consolidate message types a bit more and re-use as much as possible across types - using generics to set the data type.

@rhysmorgan134 let me know what you think of this change :) 

I also moved the pi 5 config detection code to a separate method - looks like this was the intent with the enums.

Also it seems that the eslint/prettier config are not applied and my vscode setup automatically applies them when saving files, which changed indentation and formatting across files i touched

### CODE REVIEW

**Comment by rhysmorgan134** [comment]
Thanks Yoni, indeed my webstorm IDE defaults to prettier off, I forgot to do it everytime!

**Comment by rhysmorgan134** [comment]
@gozmanyoni what do you think about putting the explorer parts in the example server? It could always be listening for the UDP server find message then, and if it gets received then sets up the socket.io server?

It feels like it would always be present for remote diagnostic then

**Comment by rhysmorgan134** [comment]
Or if you even have any thoughts on the current set up of everything. I have gone for the unix socket to allow any language to be used on the application side. I'm not precious about doing it that way, just seems the most open method.

**Comment by gozmanyoni** [comment]
@rhysmorgan134 hmm - with the explorer server, it does make sense to me to put it there - and perhaps have it enabled as a config option? (can also listen to the udp event to actually start it) - but consumers might not want/need that.

**Pull request merged**
